---
title: "EUN SHIN DATA VISUALIZATION"
output: pdf_document
---

DATE: 2015-01-29
---

##**TASK** <br>
The Nigerian Government has committed $1.2 billion USD to achieving the United Nations Millennium Development Goals. Matching grants are given to Local Government Areas (LGAs) for approved projects and programmes geared towards reducing poverty and improving education and health. To promote the use of data in the local planning process, a rigorous, geo-referenced, baseline facility inventory was conducted for the entire country. The objective was to collect data for all of Nigeria’s health, education and water facilities. The result is this online portal, the Nigeria MDG Information System (NMIS).

Using this rich dataset, we will assess a few key development statistics, previously unknowable.

- **[PART 1]**Go to this link to retrieve general metadata for Local Government Areas (LGAs) of Nigeria. LGAs are akin to counties in the U.S.Next, download the full NMIS dataset, and grab the [large] .csv file called “Health_Mopup_and_Baseline_NMIS_Facility.csv”. This contains every health facility in Nigeria.
- **[PART 2]**Produce a new data.frame with the following properties:From the NMIS Health Facilities Inventory, select all facilities located in the Southern zones of Nigeria.Incorporate LGA metadata into this new dataframe.
- **[PART 3]**Calculate the total number of full time nurses and doctors for all health facilities, by state. Compute per capita and per area values, as well.
Sort the resulting dataset by state population, in descending order.
Show the results!

##**SOLUTION**
Before I run R for the assignment, I activated some packages using `library()` that might be needed ro run my codes. 

```
library("ggplot2", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("plyr", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("xlsx", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("reshape2", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
library("markdown", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")
```
For **PART 1** of the assignemnt,I downloaded the two data sets in my working directory. For **PART 2** I merged the two data files by the `unique_lga` variable. Then, to select all facilities located in the Southern zones of Nigeria, I made the subset of the data which I names as `newdata`. Also I omitted missing variables. 

```
setwd("/Users/eunkyongshin/GitHub/data-viz/r")
lgas<-read.csv("lgas.csv")
nmis<- read.csv("Health_Mopup_and_Baseline_NMIS_Facility.csv")
data<-merge(nmis, lgas, by="unique_lga")
newdata<-subset(data, zone %in% c("South-South","Southeast","Southwest"))
newdata<-na.omit(newdata)


```

For coding efficiency, I costomized value names. Also by creating new variable `nurse` I added up the `num_nurses_fulltime` and `num_nursemidwives_fulltime` to use it as the total number of full time nurses.   

``` 
newdata<-rename(newdata,c(num_nurses_fulltime="nurs"))
newdata<-rename(newdata,c(num_nursemidwives_fulltime="midw"))
newdata<-rename(newdata,c(num_doctors_fulltime="doctor"))
newdata<-rename(newdata,c(facility_name="facility"))
newdata<-rename(newdata,c(pop_2006="popu"))
newdata<-rename(newdata,c(area_sq_km="area"))
newdata$nurse<-newdata$nurs+newdata$midw
```

Next,in **PART 3** I created two subsets that willl merged as `statedata` at the end. The first subset, `mydata1` contains facilities only in the southern part of Nigeria, The `finaldata` contains informations of the total full time nurses and doctors for all health dacilities in the Southern Zones of Nigeria.  

```{r}
myvars<-c("facility","nurse","doctor","state","zone","area","popu")
mydata1<-newdata[myvars]
head(mydata1)
```
Then now to answer the **PART 3** of the assignment, I will create a variable that will 


Then, I created tables to calculate the total numbers of nurses and doctors by states. 
```
ddply(mydata,.(state),numcolwise(sum))
## To calculate, sum of the numbers of nurses and doctors
attach(mydata)
mynurstable<-table(state,nurse)
nurse<-margin.table(mynurstable,1)
nurse
mydocttable<-table(state, doctor)
doctor<-margin.table(mydocttable,1)

```
Then, finally I save the data as a saparate data file. 
```
statedata<-c("state","area","popu")
stateinfo<-mydata[statedata]

stateinfo1<-unique(stateinfo)
stateinfo1
write.csv(stateinfo1, file="stateunique.csv")
su<-read.csv("stateunique.csv")

attach(su)
areatable<-table(state,area)
area<-margin.table(areatable,1)
areatable

ddply(su,.(state),numcolwise(sum))

```

state
---
newdata$zone[newdata$zone == "North-Central"]<-"na"
newdata$zone[newdata$zone == "Northwest"]<-"na"
newdata$zone[newdata$zone == "Northeast"]<-"na"
newdata$zone[newdata$zone == "South-South"]<-"s"
newdata$zone[newdata$zone == "Southeast"]<-"s"
newdata$zone[newdata$zone == "Southwest"]<-"s"

newdata$zone <- as.character(newdata$zone)
str(newdata)
newdata<-na.omit(newdata) ## missing data
finaldata<-subset(mydata, zone == "South-South"|"Southeast"|"Southwest")
finaldata$zone <- as.factor(finaldata$zone)
str(finaldata)
finaldata<-na.omit(finaldata)